version: "3.7"
services:
  app:
    container_name: currencycrawler-laravel-app-dev
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    image: ejklock/php-fpm:8.1
    networks:
      - currencycrawler-laravelNetwork
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ./docker-compose/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/app
    depends_on:
      - "db"
  db:
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp --max_connections=256
    container_name: currencycrawler-laravel-dev-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    image: mysql:5.7-oracle
    networks:
      - currencycrawler-laravelNetwork
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - currencycrawler-laravelMysqlData:/var/lib/mysql
  nginx:
    container_name: currencycrawler-laravel-dev-nginx
    image: nginx:alpine
    networks:
      - currencycrawler-laravelNetwork
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    working_dir: /var/www/app
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - currencycrawler-laravelNetwork
networks:
  currencycrawler-laravelNetwork:
    driver: bridge
volumes:
  currencycrawler-laravelMysqlData:
    driver: local
    name: currencycrawler-laravelMysqlData
